### ISSUE TITLE
Client freezes every few minutes

### ISSUE THREAD

**Issue by QnQuera** [Reetus/ClassicAssist#353] opened 2023-02-26 15:23 UTC
please excuse my english, i am not english speaking :D

**Information**
ClassicUO Version: 0.1.11.21
ClassicAssist Version: 0.4.413
Client Version: custom launcher https://uoeclipse.com/
Shard: UO Eclipse

**Describe the bug**
My clients freeze as soon as I play on the shard with Classic Assist. Many players are affected by the problem, when you ask about it, the first thing you usually hear is.... Install Razor Enhanced, then you won't have the problem. 
Unfortunately that's true.. I had played with CA on day one and tested several versions, from very old to very new. 
In the meantime I have the above configuaration, all 4 clients split into their own installations. All point to the UO client data of the custom launcher, but all use the latest versions. 
When one is online alone, the connection lasts a bit longer, but eventually it also freezes. 
Today I've had everything from "client just closes" to "CUO.Exe has a problem and needs to be restarted" to "frozen client that you don't notice until you move". 

With the following script I can at least work around the freeze error and get logged in again right away, but unfortunately that's not very satisfying :( 

```
SetAutologin(False)  
cnt = 0
while True: 
    check = Ping()
    print check
    Pause(500)
    if check != -1:
        cnt = 0
        Pause(500)
        print check
    else:
        print cnt
        if cnt < 4:
            cnt += 1
        else: 
            SetAutologin(True,'ACCOUNTNAME') 
            Pause(200)
            Logout()
    Pause(5000)
```

**To Reproduce**
If you search for freeze/aborts in the Discord channel of Eclipse, you will find some people who are affected by this. In itself it is enough to log in with more than one client and wait. The freezes happen mostly to the chars that are standing around afk. 
But it also happens to the active ones after a certain time. Today i tested about 3 hours and now every few minutes one client is frozen :( 

I switched to Razor Enhanced, because a bug-free game is more fun. However, I miss your ingenious assistant, so I set up a test environment again today and hoped it would be better, but unfortunately no chance . I would be very happy if you take a closer look at the problem. If I can provide any information or I should test something, I am very happy to do so.

**Comment by Reetus** [comment] 2023-02-26 18:31
Duplicate of https://github.com/Reetus/ClassicAssist/issues/241

**Closed by Reetus** 2023-02-26 18:31 UTC
